### PR TITLE
Fix typo preventing build

### PR DESCRIPTION
**Pull request by reznakt**
Fixes a typo introduced in 7b339a5 (v5.15.0), which results in the following error when building my project with `tsc`:

```ts
node_modules/.pnpm/systeminformation@5.15.0/node_modules/systeminformation/lib/index.d.ts:1013:96 - error TS2833: Cannot find namespace 'ysteminformation'. Did you mean 'Systeminformation'?

1013 export function getDynamicData(srv?: string, iface?: string, cb?: (data: any) => any): Promise<ysteminformation.DynamicData>;
```

### CODE REVIEW

**Comment by sebhildebrandt** [comment]
@reznakt sorry!!! My fault! Fixed, Version 5.15.1 just released
